" abbreviations for unicode emoji
abbreviate :smile:                                                           😄
abbreviate :smiley:                                                          😃
abbreviate :grinning:                                                        😀
abbreviate :blush:                                                           😊
abbreviate :relaxed:                                                          ☺️ 
abbreviate :wink:                                                            😉
abbreviate :heart_eyes:                                                      😍
abbreviate :kissing_heart:                                                   😘
abbreviate :kissing_closed_eyes:                                             😚
abbreviate :kissing:                                                         😗
abbreviate :kissing_smiling_eyes:                                            😙
abbreviate :stuck_out_tongue_winking_eye:                                    😜
abbreviate :stuck_out_tongue_closed_eyes:                                    😝
abbreviate :stuck_out_tongue:                                                😛
abbreviate :flushed:                                                         😳
abbreviate :grin:                                                            😁
abbreviate :pensive:                                                         😔
abbreviate :relieved:                                                        😌
abbreviate :unamused:                                                        😒
abbreviate :disappointed:                                                    😞
abbreviate :persevere:                                                       😣
abbreviate :cry:                                                             😢
abbreviate :joy:                                                             😂
abbreviate :sob:                                                             😭
abbreviate :sleepy:                                                          😪
abbreviate :disappointed_relieved:                                           😥
abbreviate :cold_sweat:                                                      😰
abbreviate :sweat_smile:                                                     😅
abbreviate :sweat:                                                           😓
abbreviate :weary:                                                           😩
abbreviate :tired_face:                                                      😫
abbreviate :fearful:                                                         😨
abbreviate :scream:                                                          😱
abbreviate :angry:                                                           😠
abbreviate :rage:                                                            😡
abbreviate :triumph:                                                         😤
abbreviate :confounded:                                                      😖
abbreviate :laughing:                                                        😆
abbreviate :satisfied:                                                       😆
abbreviate :yum:                                                             😋
abbreviate :mask:                                                            😷
abbreviate :sunglasses:                                                      😎
abbreviate :sleeping:                                                        😴
abbreviate :dizzy_face:                                                      😵
abbreviate :astonished:                                                      😲
abbreviate :worried:                                                         😟
abbreviate :frowning:                                                        😦
abbreviate :anguished:                                                       😧
abbreviate :smiling_imp:                                                     😈
abbreviate :imp:                                                             👿
abbreviate :open_mouth:                                                      😮
abbreviate :grimacing:                                                       😬
abbreviate :neutral_face:                                                    😐
abbreviate :confused:                                                        😕
abbreviate :hushed:                                                          😯
abbreviate :no_mouth:                                                        😶
abbreviate :innocent:                                                        😇
abbreviate :smirk:                                                           😏
abbreviate :expressionless:                                                  😑
abbreviate :man_with_gua_pi_mao:                                             👲
abbreviate :man_with_turban:                                                 👳
abbreviate :cop:                                                             👮
abbreviate :construction_worker:                                             👷
abbreviate :guardsman:                                                       💂
abbreviate :baby:                                                            👶
abbreviate :boy:                                                             👦
abbreviate :girl:                                                            👧
abbreviate :man:                                                             👨
abbreviate :woman:                                                           👩
abbreviate :older_man:                                                       👴
abbreviate :older_woman:                                                     👵
abbreviate :person_with_blond_hair:                                          👱
abbreviate :angel:                                                           👼
abbreviate :princess:                                                        👸
abbreviate :smiley_cat:                                                      😺
abbreviate :smile_cat:                                                       😸
abbreviate :heart_eyes_cat:                                                  😻
abbreviate :kissing_cat:                                                     😽
abbreviate :smirk_cat:                                                       😼
abbreviate :scream_cat:                                                      🙀
abbreviate :crying_cat_face:                                                 😿
abbreviate :joy_cat:                                                         😹
abbreviate :pouting_cat:                                                     😾
abbreviate :japanese_ogre:                                                   👹
abbreviate :japanese_goblin:                                                 👺
abbreviate :see_no_evil:                                                     🙈
abbreviate :hear_no_evil:                                                    🙉
abbreviate :speak_no_evil:                                                   🙊
abbreviate :skull:                                                           💀
abbreviate :alien:                                                           👽
abbreviate :hankey:                                                          💩
abbreviate :poop:                                                            💩
abbreviate :shit:                                                            💩
abbreviate :fire:                                                            🔥
abbreviate :sparkles:                                                         ✨ 
abbreviate :star2:                                                           🌟
abbreviate :dizzy:                                                           💫
abbreviate :boom:                                                            💥
abbreviate :collision:                                                       💥
abbreviate :anger:                                                           💢
abbreviate :sweat_drops:                                                     💦
abbreviate :droplet:                                                         💧
abbreviate :zzz:                                                             💤
abbreviate :dash:                                                            💨
abbreviate :ear:                                                             👂
abbreviate :eyes:                                                            👀
abbreviate :nose:                                                            👃
abbreviate :tongue:                                                          👅
abbreviate :lips:                                                            👄
abbreviate :+1:                                                              👍
abbreviate :thumbsup:                                                        👍
abbreviate :-1:                                                              👎
abbreviate :thumbsdown:                                                      👎
abbreviate :ok_hand:                                                         👌
abbreviate :facepunch:                                                       👊
abbreviate :punch:                                                           👊
abbreviate :fist:                                                             ✊ 
abbreviate :v:                                                                ✌️ 
abbreviate :wave:                                                            👋
abbreviate :hand:                                                             ✋ 
abbreviate :raised_hand:                                                      ✋ 
abbreviate :open_hands:                                                      👐
abbreviate :point_up_2:                                                      👆
abbreviate :point_down:                                                      👇
abbreviate :point_right:                                                     👉
abbreviate :point_left:                                                      👈
abbreviate :raised_hands:                                                    🙌
abbreviate :pray:                                                            🙏
abbreviate :point_up:                                                         ☝️ 
abbreviate :clap:                                                            👏
abbreviate :muscle:                                                          💪
abbreviate :walking:                                                         🚶
abbreviate :runner:                                                          🏃
abbreviate :running:                                                         🏃
abbreviate :dancer:                                                          💃
abbreviate :couple:                                                          👫
abbreviate :family:                                                          👪
abbreviate :two_men_holding_hands:                                           👬
abbreviate :two_women_holding_hands:                                         👭
abbreviate :couplekiss:                                                      💏
abbreviate :couple_with_heart:                                               💑
abbreviate :dancers:                                                         👯
abbreviate :ok_woman:                                                        🙆
abbreviate :no_good:                                                         🙅
abbreviate :information_desk_person:                                         💁
abbreviate :raising_hand:                                                    🙋
abbreviate :massage:                                                         💆
abbreviate :haircut:                                                         💇
abbreviate :nail_care:                                                       💅
abbreviate :bride_with_veil:                                                 👰
abbreviate :person_with_pouting_face:                                        🙎
abbreviate :person_frowning:                                                 🙍
abbreviate :bow:                                                             🙇
abbreviate :tophat:                                                          🎩
abbreviate :crown:                                                           👑
abbreviate :womans_hat:                                                      👒
abbreviate :athletic_shoe:                                                   👟
abbreviate :mans_shoe:                                                       👞
abbreviate :shoe:                                                            👞
abbreviate :sandal:                                                          👡
abbreviate :high_heel:                                                       👠
abbreviate :boot:                                                            👢
abbreviate :shirt:                                                           👕
abbreviate :tshirt:                                                          👕
abbreviate :necktie:                                                         👔
abbreviate :womans_clothes:                                                  👚
abbreviate :dress:                                                           👗
abbreviate :running_shirt_with_sash:                                         🎽
abbreviate :jeans:                                                           👖
abbreviate :kimono:                                                          👘
abbreviate :bikini:                                                          👙
abbreviate :briefcase:                                                       💼
abbreviate :handbag:                                                         👜
abbreviate :pouch:                                                           👝
abbreviate :purse:                                                           👛
abbreviate :eyeglasses:                                                      👓
abbreviate :ribbon:                                                          🎀
abbreviate :closed_umbrella:                                                 🌂
abbreviate :lipstick:                                                        💄
abbreviate :yellow_heart:                                                    💛
abbreviate :blue_heart:                                                      💙
abbreviate :purple_heart:                                                    💜
abbreviate :green_heart:                                                     💚
abbreviate :heart:                                                            ❤️ 
abbreviate :broken_heart:                                                    💔
abbreviate :heartpulse:                                                      💗
abbreviate :heartbeat:                                                       💓
abbreviate :two_hearts:                                                      💕
abbreviate :sparkling_heart:                                                 💖
abbreviate :revolving_hearts:                                                💞
abbreviate :cupid:                                                           💘
abbreviate :love_letter:                                                     💌
abbreviate :kiss:                                                            💋
abbreviate :ring:                                                            💍
abbreviate :gem:                                                             💎
abbreviate :bust_in_silhouette:                                              👤
abbreviate :busts_in_silhouette:                                             👥
abbreviate :speech_balloon:                                                  💬
abbreviate :footprints:                                                      👣
abbreviate :thought_balloon:                                                 💭
abbreviate :dog:                                                             🐶
abbreviate :wolf:                                                            🐺
abbreviate :cat:                                                             🐱
abbreviate :mouse:                                                           🐭
abbreviate :hamster:                                                         🐹
abbreviate :rabbit:                                                          🐰
abbreviate :frog:                                                            🐸
abbreviate :tiger:                                                           🐯
abbreviate :koala:                                                           🐨
abbreviate :bear:                                                            🐻
abbreviate :pig:                                                             🐷
abbreviate :pig_nose:                                                        🐽
abbreviate :cow:                                                             🐮
abbreviate :boar:                                                            🐗
abbreviate :monkey_face:                                                     🐵
abbreviate :monkey:                                                          🐒
abbreviate :horse:                                                           🐴
abbreviate :sheep:                                                           🐑
abbreviate :elephant:                                                        🐘
abbreviate :panda_face:                                                      🐼
abbreviate :penguin:                                                         🐧
abbreviate :bird:                                                            🐦
abbreviate :baby_chick:                                                      🐤
abbreviate :hatched_chick:                                                   🐥
abbreviate :hatching_chick:                                                  🐣
abbreviate :chicken:                                                         🐔
abbreviate :snake:                                                           🐍
abbreviate :turtle:                                                          🐢
abbreviate :bug:                                                             🐛
abbreviate :bee:                                                             🐝
abbreviate :honeybee:                                                        🐝
abbreviate :ant:                                                             🐜
abbreviate :beetle:                                                          🐞
abbreviate :snail:                                                           🐌
abbreviate :octopus:                                                         🐙
abbreviate :shell:                                                           🐚
abbreviate :tropical_fish:                                                   🐠
abbreviate :fish:                                                            🐟
abbreviate :dolphin:                                                         🐬
abbreviate :flipper:                                                         🐬
abbreviate :whale:                                                           🐳
abbreviate :whale2:                                                          🐋
abbreviate :cow2:                                                            🐄
abbreviate :ram:                                                             🐏
abbreviate :rat:                                                             🐀
abbreviate :water_buffalo:                                                   🐃
abbreviate :tiger2:                                                          🐅
abbreviate :rabbit2:                                                         🐇
abbreviate :dragon:                                                          🐉
abbreviate :racehorse:                                                       🐎
abbreviate :goat:                                                            🐐
abbreviate :rooster:                                                         🐓
abbreviate :dog2:                                                            🐕
abbreviate :pig2:                                                            🐖
abbreviate :mouse2:                                                          🐁
abbreviate :ox:                                                              🐂
abbreviate :dragon_face:                                                     🐲
abbreviate :blowfish:                                                        🐡
abbreviate :crocodile:                                                       🐊
abbreviate :camel:                                                           🐫
abbreviate :dromedary_camel:                                                 🐪
abbreviate :leopard:                                                         🐆
abbreviate :cat2:                                                            🐈
abbreviate :poodle:                                                          🐩
abbreviate :feet:                                                            🐾
abbreviate :paw_prints:                                                      🐾
abbreviate :bouquet:                                                         💐
abbreviate :cherry_blossom:                                                  🌸
abbreviate :tulip:                                                           🌷
abbreviate :four_leaf_clover:                                                🍀
abbreviate :rose:                                                            🌹
abbreviate :sunflower:                                                       🌻
abbreviate :hibiscus:                                                        🌺
abbreviate :maple_leaf:                                                      🍁
abbreviate :leaves:                                                          🍃
abbreviate :fallen_leaf:                                                     🍂
abbreviate :herb:                                                            🌿
abbreviate :ear_of_rice:                                                     🌾
abbreviate :mushroom:                                                        🍄
abbreviate :cactus:                                                          🌵
abbreviate :palm_tree:                                                       🌴
abbreviate :evergreen_tree:                                                  🌲
abbreviate :deciduous_tree:                                                  🌳
abbreviate :chestnut:                                                        🌰
abbreviate :seedling:                                                        🌱
abbreviate :blossom:                                                         🌼
abbreviate :globe_with_meridians:                                            🌐
abbreviate :sun_with_face:                                                   🌞
abbreviate :full_moon_with_face:                                             🌝
abbreviate :new_moon_with_face:                                              🌚
abbreviate :new_moon:                                                        🌑
abbreviate :waxing_crescent_moon:                                            🌒
abbreviate :first_quarter_moon:                                              🌓
abbreviate :moon:                                                            🌔
abbreviate :waxing_gibbous_moon:                                             🌔
abbreviate :full_moon:                                                       🌕
abbreviate :waning_gibbous_moon:                                             🌖
abbreviate :last_quarter_moon:                                               🌗
abbreviate :waning_crescent_moon:                                            🌘
abbreviate :last_quarter_moon_with_face:                                     🌜
abbreviate :first_quarter_moon_with_face:                                    🌛
abbreviate :crescent_moon:                                                   🌙
abbreviate :earth_africa:                                                    🌍
abbreviate :earth_americas:                                                  🌎
abbreviate :earth_asia:                                                      🌏
abbreviate :volcano:                                                         🌋
abbreviate :milky_way:                                                       🌌
abbreviate :stars:                                                           🌠
abbreviate :star:                                                             ⭐ 
abbreviate :sunny:                                                            ☀️ 
abbreviate :partly_sunny:                                                     ⛅ 
abbreviate :cloud:                                                            ☁️ 
abbreviate :zap:                                                              ⚡ 
abbreviate :umbrella:                                                         ☔ 
abbreviate :snowflake:                                                        ❄️ 
abbreviate :snowman:                                                          ⛄ 
abbreviate :cyclone:                                                         🌀
abbreviate :foggy:                                                           🌁
abbreviate :rainbow:                                                         🌈
abbreviate :ocean:                                                           🌊
abbreviate :bamboo:                                                          🎍
abbreviate :gift_heart:                                                      💝
abbreviate :dolls:                                                           🎎
abbreviate :school_satchel:                                                  🎒
abbreviate :mortar_board:                                                    🎓
abbreviate :flags:                                                           🎏
abbreviate :fireworks:                                                       🎆
abbreviate :sparkler:                                                        🎇
abbreviate :wind_chime:                                                      🎐
abbreviate :rice_scene:                                                      🎑
abbreviate :jack_o_lantern:                                                  🎃
abbreviate :ghost:                                                           👻
abbreviate :santa:                                                           🎅
abbreviate :christmas_tree:                                                  🎄
abbreviate :gift:                                                            🎁
abbreviate :tanabata_tree:                                                   🎋
abbreviate :tada:                                                            🎉
abbreviate :confetti_ball:                                                   🎊
abbreviate :balloon:                                                         🎈
abbreviate :crossed_flags:                                                   🎌
abbreviate :crystal_ball:                                                    🔮
abbreviate :movie_camera:                                                    🎥
abbreviate :camera:                                                          📷
abbreviate :video_camera:                                                    📹
abbreviate :vhs:                                                             📼
abbreviate :cd:                                                              💿
abbreviate :dvd:                                                             📀
abbreviate :minidisc:                                                        💽
abbreviate :floppy_disk:                                                     💾
abbreviate :computer:                                                        💻
abbreviate :iphone:                                                          📱
abbreviate :phone:                                                            ☎️ 
abbreviate :telephone:                                                        ☎️ 
abbreviate :telephone_receiver:                                              📞
abbreviate :pager:                                                           📟
abbreviate :fax:                                                             📠
abbreviate :satellite:                                                       📡
abbreviate :tv:                                                              📺
abbreviate :radio:                                                           📻
abbreviate :loud_sound:                                                      🔊
abbreviate :sound:                                                           🔉
abbreviate :speaker:                                                         🔈
abbreviate :mute:                                                            🔇
abbreviate :bell:                                                            🔔
abbreviate :no_bell:                                                         🔕
abbreviate :loudspeaker:                                                     📢
abbreviate :mega:                                                            📣
abbreviate :hourglass_flowing_sand:                                           ⏳ 
abbreviate :hourglass:                                                        ⌛ 
abbreviate :alarm_clock:                                                      ⏰ 
abbreviate :watch:                                                            ⌚ 
abbreviate :unlock:                                                          🔓
abbreviate :lock:                                                            🔒
abbreviate :lock_with_ink_pen:                                               🔏
abbreviate :closed_lock_with_key:                                            🔐
abbreviate :key:                                                             🔑
abbreviate :mag_right:                                                       🔎
abbreviate :bulb:                                                            💡
abbreviate :flashlight:                                                      🔦
abbreviate :high_brightness:                                                 🔆
abbreviate :low_brightness:                                                  🔅
abbreviate :electric_plug:                                                   🔌
abbreviate :battery:                                                         🔋
abbreviate :mag:                                                             🔍
abbreviate :bathtub:                                                         🛁
abbreviate :bath:                                                            🛀
abbreviate :shower:                                                          🚿
abbreviate :toilet:                                                          🚽
abbreviate :wrench:                                                          🔧
abbreviate :nut_and_bolt:                                                    🔩
abbreviate :hammer:                                                          🔨
abbreviate :door:                                                            🚪
abbreviate :smoking:                                                         🚬
abbreviate :bomb:                                                            💣
abbreviate :gun:                                                             🔫
abbreviate :hocho:                                                           🔪
abbreviate :knife:                                                           🔪
abbreviate :pill:                                                            💊
abbreviate :syringe:                                                         💉
abbreviate :moneybag:                                                        💰
abbreviate :yen:                                                             💴
abbreviate :dollar:                                                          💵
abbreviate :pound:                                                           💷
abbreviate :euro:                                                            💶
abbreviate :credit_card:                                                     💳
abbreviate :money_with_wings:                                                💸
abbreviate :calling:                                                         📲
abbreviate :e-mail:                                                          📧
abbreviate :inbox_tray:                                                      📥
abbreviate :outbox_tray:                                                     📤
abbreviate :email:                                                            ✉️ 
abbreviate :envelope:                                                         ✉️ 
abbreviate :envelope_with_arrow:                                             📩
abbreviate :incoming_envelope:                                               📨
abbreviate :postal_horn:                                                     📯
abbreviate :mailbox:                                                         📫
abbreviate :mailbox_closed:                                                  📪
abbreviate :mailbox_with_mail:                                               📬
abbreviate :mailbox_with_no_mail:                                            📭
abbreviate :postbox:                                                         📮
abbreviate :package:                                                         📦
abbreviate :memo:                                                            📝
abbreviate :pencil:                                                          📝
abbreviate :page_facing_up:                                                  📄
abbreviate :page_with_curl:                                                  📃
abbreviate :bookmark_tabs:                                                   📑
abbreviate :bar_chart:                                                       📊
abbreviate :chart_with_upwards_trend:                                        📈
abbreviate :chart_with_downwards_trend:                                      📉
abbreviate :scroll:                                                          📜
abbreviate :clipboard:                                                       📋
abbreviate :date:                                                            📅
abbreviate :calendar:                                                        📆
abbreviate :card_index:                                                      📇
abbreviate :file_folder:                                                     📁
abbreviate :open_file_folder:                                                📂
abbreviate :scissors:                                                         ✂️ 
abbreviate :pushpin:                                                         📌
abbreviate :paperclip:                                                       📎
abbreviate :black_nib:                                                        ✒️ 
abbreviate :pencil2:                                                          ✏️ 
abbreviate :straight_ruler:                                                  📏
abbreviate :triangular_ruler:                                                📐
abbreviate :closed_book:                                                     📕
abbreviate :green_book:                                                      📗
abbreviate :blue_book:                                                       📘
abbreviate :orange_book:                                                     📙
abbreviate :notebook:                                                        📓
abbreviate :notebook_with_decorative_cover:                                  📔
abbreviate :ledger:                                                          📒
abbreviate :books:                                                           📚
abbreviate :book:                                                            📖
abbreviate :open_book:                                                       📖
abbreviate :bookmark:                                                        🔖
abbreviate :name_badge:                                                      📛
abbreviate :microscope:                                                      🔬
abbreviate :telescope:                                                       🔭
abbreviate :newspaper:                                                       📰
abbreviate :art:                                                             🎨
abbreviate :clapper:                                                         🎬
abbreviate :microphone:                                                      🎤
abbreviate :headphones:                                                      🎧
abbreviate :musical_score:                                                   🎼
abbreviate :musical_note:                                                    🎵
abbreviate :notes:                                                           🎶
abbreviate :musical_keyboard:                                                🎹
abbreviate :violin:                                                          🎻
abbreviate :trumpet:                                                         🎺
abbreviate :saxophone:                                                       🎷
abbreviate :guitar:                                                          🎸
abbreviate :space_invader:                                                   👾
abbreviate :video_game:                                                      🎮
abbreviate :black_joker:                                                     🃏
abbreviate :flower_playing_cards:                                            🎴
abbreviate :mahjong:                                                         🀄
abbreviate :game_die:                                                        🎲
abbreviate :dart:                                                            🎯
abbreviate :football:                                                        🏈
abbreviate :basketball:                                                      🏀
abbreviate :soccer:                                                           ⚽ 
abbreviate :baseball:                                                         ⚾️ 
abbreviate :tennis:                                                          🎾
abbreviate :8ball:                                                           🎱
abbreviate :rugby_football:                                                  🏉
abbreviate :bowling:                                                         🎳
abbreviate :golf:                                                             ⛳ 
abbreviate :mountain_bicyclist:                                              🚵
abbreviate :bicyclist:                                                       🚴
abbreviate :checkered_flag:                                                  🏁
abbreviate :horse_racing:                                                    🏇
abbreviate :trophy:                                                          🏆
abbreviate :ski:                                                             🎿
abbreviate :snowboarder:                                                     🏂
abbreviate :swimmer:                                                         🏊
abbreviate :surfer:                                                          🏄
abbreviate :fishing_pole_and_fish:                                           🎣
abbreviate :coffee:                                                           ☕ 
abbreviate :tea:                                                             🍵
abbreviate :sake:                                                            🍶
abbreviate :baby_bottle:                                                     🍼
abbreviate :beer:                                                            🍺
abbreviate :beers:                                                           🍻
abbreviate :cocktail:                                                        🍸
abbreviate :tropical_drink:                                                  🍹
abbreviate :wine_glass:                                                      🍷
abbreviate :fork_and_knife:                                                  🍴
abbreviate :pizza:                                                           🍕
abbreviate :hamburger:                                                       🍔
abbreviate :fries:                                                           🍟
abbreviate :poultry_leg:                                                     🍗
abbreviate :meat_on_bone:                                                    🍖
abbreviate :spaghetti:                                                       🍝
abbreviate :curry:                                                           🍛
abbreviate :fried_shrimp:                                                    🍤
abbreviate :bento:                                                           🍱
abbreviate :sushi:                                                           🍣
abbreviate :fish_cake:                                                       🍥
abbreviate :rice_ball:                                                       🍙
abbreviate :rice_cracker:                                                    🍘
abbreviate :rice:                                                            🍚
abbreviate :ramen:                                                           🍜
abbreviate :stew:                                                            🍲
abbreviate :oden:                                                            🍢
abbreviate :dango:                                                           🍡
abbreviate :egg:                                                             🍳
abbreviate :bread:                                                           🍞
abbreviate :doughnut:                                                        🍩
abbreviate :custard:                                                         🍮
abbreviate :icecream:                                                        🍦
abbreviate :ice_cream:                                                       🍨
abbreviate :shaved_ice:                                                      🍧
abbreviate :birthday:                                                        🎂
abbreviate :cake:                                                            🍰
abbreviate :cookie:                                                          🍪
abbreviate :chocolate_bar:                                                   🍫
abbreviate :candy:                                                           🍬
abbreviate :lollipop:                                                        🍭
abbreviate :honey_pot:                                                       🍯
abbreviate :apple:                                                           🍎
abbreviate :green_apple:                                                     🍏
abbreviate :tangerine:                                                       🍊
abbreviate :lemon:                                                           🍋
abbreviate :cherries:                                                        🍒
abbreviate :grapes:                                                          🍇
abbreviate :watermelon:                                                      🍉
abbreviate :strawberry:                                                      🍓
abbreviate :peach:                                                           🍑
abbreviate :melon:                                                           🍈
abbreviate :banana:                                                          🍌
abbreviate :pear:                                                            🍐
abbreviate :pineapple:                                                       🍍
abbreviate :sweet_potato:                                                    🍠
abbreviate :eggplant:                                                        🍆
abbreviate :tomato:                                                          🍅
abbreviate :corn:                                                            🌽
abbreviate :house:                                                           🏠
abbreviate :house_with_garden:                                               🏡
abbreviate :school:                                                          🏫
abbreviate :office:                                                          🏢
abbreviate :post_office:                                                     🏣
abbreviate :hospital:                                                        🏥
abbreviate :bank:                                                            🏦
abbreviate :convenience_store:                                               🏪
abbreviate :love_hotel:                                                      🏩
abbreviate :hotel:                                                           🏨
abbreviate :wedding:                                                         💒
abbreviate :church:                                                           ⛪ 
abbreviate :department_store:                                                🏬
abbreviate :european_post_office:                                            🏤
abbreviate :city_sunrise:                                                    🌇
abbreviate :city_sunset:                                                     🌆
abbreviate :japanese_castle:                                                 🏯
abbreviate :european_castle:                                                 🏰
abbreviate :tent:                                                             ⛺ 
abbreviate :factory:                                                         🏭
abbreviate :tokyo_tower:                                                     🗼
abbreviate :japan:                                                           🗾
abbreviate :mount_fuji:                                                      🗻
abbreviate :sunrise_over_mountains:                                          🌄
abbreviate :sunrise:                                                         🌅
abbreviate :night_with_stars:                                                🌃
abbreviate :statue_of_liberty:                                               🗽
abbreviate :bridge_at_night:                                                 🌉
abbreviate :carousel_horse:                                                  🎠
abbreviate :ferris_wheel:                                                    🎡
abbreviate :fountain:                                                         ⛲ 
abbreviate :roller_coaster:                                                  🎢
abbreviate :ship:                                                            🚢
abbreviate :boat:                                                             ⛵ 
abbreviate :sailboat:                                                         ⛵ 
abbreviate :speedboat:                                                       🚤
abbreviate :rowboat:                                                         🚣
abbreviate :anchor:                                                           ⚓ 
abbreviate :rocket:                                                          🚀
abbreviate :airplane:                                                         ✈️ 
abbreviate :seat:                                                            💺
abbreviate :helicopter:                                                      🚁
abbreviate :steam_locomotive:                                                🚂
abbreviate :tram:                                                            🚊
abbreviate :station:                                                         🚉
abbreviate :mountain_railway:                                                🚞
abbreviate :train2:                                                          🚆
abbreviate :bullettrain_side:                                                🚄
abbreviate :bullettrain_front:                                               🚅
abbreviate :light_rail:                                                      🚈
abbreviate :metro:                                                           🚇
abbreviate :monorail:                                                        🚝
abbreviate :train:                                                           🚋
abbreviate :railway_car:                                                     🚃
abbreviate :trolleybus:                                                      🚎
abbreviate :bus:                                                             🚌
abbreviate :oncoming_bus:                                                    🚍
abbreviate :blue_car:                                                        🚙
abbreviate :oncoming_automobile:                                             🚘
abbreviate :car:                                                             🚗
abbreviate :red_car:                                                         🚗
abbreviate :taxi:                                                            🚕
abbreviate :oncoming_taxi:                                                   🚖
abbreviate :articulated_lorry:                                               🚛
abbreviate :truck:                                                           🚚
abbreviate :rotating_light:                                                  🚨
abbreviate :police_car:                                                      🚓
abbreviate :oncoming_police_car:                                             🚔
abbreviate :fire_engine:                                                     🚒
abbreviate :ambulance:                                                       🚑
abbreviate :minibus:                                                         🚐
abbreviate :bike:                                                            🚲
abbreviate :aerial_tramway:                                                  🚡
abbreviate :suspension_railway:                                              🚟
abbreviate :mountain_cableway:                                               🚠
abbreviate :tractor:                                                         🚜
abbreviate :barber:                                                          💈
abbreviate :busstop:                                                         🚏
abbreviate :ticket:                                                          🎫
abbreviate :vertical_traffic_light:                                          🚦
abbreviate :traffic_light:                                                   🚥
abbreviate :warning:                                                          ⚠️ 
abbreviate :construction:                                                    🚧
abbreviate :beginner:                                                        🔰
abbreviate :fuelpump:                                                         ⛽ 
abbreviate :izakaya_lantern:                                                 🏮
abbreviate :lantern:                                                         🏮
abbreviate :slot_machine:                                                    🎰
abbreviate :hotsprings:                                                       ♨️ 
abbreviate :moyai:                                                           🗿
abbreviate :circus_tent:                                                     🎪
abbreviate :performing_arts:                                                 🎭
abbreviate :round_pushpin:                                                   📍
abbreviate :triangular_flag_on_post:                                         🚩
abbreviate🇵 :jp:                                                            🇯
abbreviate🇷 :kr:                                                            🇰
abbreviate🇪 :de:                                                            🇩
abbreviate🇳 :cn:                                                            🇨
abbreviate🇸 :us:                                                            🇺
abbreviate🇷 :fr:                                                            🇫
abbreviate🇸 :es:                                                            🇪
abbreviate🇹 :it:                                                            🇮
abbreviate🇺 :ru:                                                            🇷
abbreviate🇧 :gb:                                                            🇬
abbreviate🇧 :uk:                                                            🇬
abbreviate :one:                                                              1️⃣ 
abbreviate :two:                                                              2️⃣ 
abbreviate :three:                                                            3️⃣ 
abbreviate :four:                                                             4️⃣ 
abbreviate :five:                                                             5️⃣ 
abbreviate :six:                                                              6️⃣ 
abbreviate :seven:                                                            7️⃣ 
abbreviate :eight:                                                            8️⃣ 
abbreviate :nine:                                                             9️⃣ 
abbreviate :zero:                                                             0️⃣ 
abbreviate :keycap_ten:                                                      🔟
abbreviate :1234:                                                            🔢
abbreviate :hash:                                                             #️⃣ 
abbreviate :symbols:                                                         🔣
abbreviate :arrow_up:                                                         ⬆️ 
abbreviate :arrow_down:                                                       ⬇️ 
abbreviate :arrow_left:                                                       ⬅️ 
abbreviate :arrow_right:                                                      ➡️ 
abbreviate :capital_abcd:                                                    🔠
abbreviate :abcd:                                                            🔡
abbreviate :abc:                                                             🔤
abbreviate :arrow_upper_right:                                                ↗️ 
abbreviate :arrow_upper_left:                                                 ↖️ 
abbreviate :arrow_lower_right:                                                ↘️ 
abbreviate :arrow_lower_left:                                                 ↙️ 
abbreviate :left_right_arrow:                                                 ↔️ 
abbreviate :arrow_up_down:                                                    ↕️ 
abbreviate :arrows_counterclockwise:                                         🔄
abbreviate :arrow_backward:                                                   ◀️ 
abbreviate :arrow_forward:                                                    ▶️ 
abbreviate :arrow_up_small:                                                  🔼
abbreviate :arrow_down_small:                                                🔽
abbreviate :leftwards_arrow_with_hook:                                        ↩️ 
abbreviate :arrow_right_hook:                                                 ↪️ 
abbreviate :information_source:                                               ℹ️ 
abbreviate :rewind:                                                           ⏪ 
abbreviate :fast_forward:                                                     ⏩ 
abbreviate :arrow_double_up:                                                  ⏫ 
abbreviate :arrow_double_down:                                                ⏬ 
abbreviate :arrow_heading_down:                                               ⤵️ 
abbreviate :arrow_heading_up:                                                 ⤴️ 
abbreviate :ok:                                                               🆗 
abbreviate :twisted_rightwards_arrows:                                       🔀
abbreviate :repeat:                                                          🔁
abbreviate :repeat_one:                                                      🔂
abbreviate :new:                                                              🆕 
abbreviate :up:                                                               🆙 
abbreviate :cool:                                                             🆒 
abbreviate :free:                                                             🆓 
abbreviate :ng:                                                               🆖 
abbreviate :signal_strength:                                                 📶
abbreviate :cinema:                                                          🎦
abbreviate :koko:                                                            🈁
abbreviate :u6307:                                                           🈯
abbreviate :u7a7a:                                                           🈳
abbreviate :u6e80:                                                           🈵
abbreviate :u5408:                                                           🈴
abbreviate :u7981:                                                           🈲
abbreviate :ideograph_advantage:                                             🉐
abbreviate :u5272:                                                           🈹
abbreviate :u55b6:                                                           🈺
abbreviate :u6709:                                                           🈶
abbreviate :u7121:                                                           🈚
abbreviate :restroom:                                                        🚻
abbreviate :mens:                                                            🚹
abbreviate :womens:                                                          🚺
abbreviate :baby_symbol:                                                     🚼
abbreviate :wc:                                                              🚾
abbreviate :potable_water:                                                   🚰
abbreviate :put_litter_in_its_place:                                         🚮
abbreviate :parking:                                                          🅿️ 
abbreviate :wheelchair:                                                       ♿ 
abbreviate :no_smoking:                                                      🚭
abbreviate :u6708:                                                           🈷️
abbreviate :u7533:                                                           🈸
abbreviate :sa:                                                              🈂️
abbreviate :m:                                                                Ⓜ️ 
abbreviate :passport_control:                                                🛂
abbreviate :baggage_claim:                                                   🛄
abbreviate :left_luggage:                                                    🛅
abbreviate :customs:                                                         🛃
abbreviate :accept:                                                          🉑
abbreviate :secret:                                                          ㊙️
abbreviate :congratulations:                                                 ㊗️
abbreviate :cl:                                                               🆑 
abbreviate :sos:                                                              🆘 
abbreviate :id:                                                               🆔 
abbreviate :no_entry_sign:                                                   🚫
abbreviate :underage:                                                        🔞
abbreviate :no_mobile_phones:                                                📵
abbreviate :do_not_litter:                                                   🚯
abbreviate :non-potable_water:                                               🚱
abbreviate :no_bicycles:                                                     🚳
abbreviate :no_pedestrians:                                                  🚷
abbreviate :children_crossing:                                               🚸
abbreviate :no_entry:                                                         ⛔ 
abbreviate :eight_spoked_asterisk:                                            ✳️ 
abbreviate :sparkle:                                                          ❇️ 
abbreviate :negative_squared_cross_mark:                                      ❎ 
abbreviate :white_check_mark:                                                 ✅ 
abbreviate :eight_pointed_black_star:                                         ✴️ 
abbreviate :heart_decoration:                                                💟
abbreviate :vs:                                                               🆚 
abbreviate :vibration_mode:                                                  📳
abbreviate :mobile_phone_off:                                                📴
abbreviate :a:                                                                🅰️ 
abbreviate :b:                                                                🅱️ 
abbreviate :ab:                                                               🆎 
abbreviate :o2:                                                               🅾️ 
abbreviate :diamond_shape_with_a_dot_inside:                                 💠
abbreviate :loop:                                                             ➿ 
abbreviate :recycle:                                                          ♻️ 
abbreviate :aries:                                                            ♈ 
abbreviate :taurus:                                                           ♉ 
abbreviate :gemini:                                                           ♊ 
abbreviate :cancer:                                                           ♋ 
abbreviate :leo:                                                              ♌ 
abbreviate :virgo:                                                            ♍ 
abbreviate :libra:                                                            ♎ 
abbreviate :scorpius:                                                         ♏ 
abbreviate :sagittarius:                                                      ♐ 
abbreviate :capricorn:                                                        ♑ 
abbreviate :aquarius:                                                         ♒ 
abbreviate :pisces:                                                           ♓ 
abbreviate :ophiuchus:                                                        ⛎ 
abbreviate :six_pointed_star:                                                🔯
abbreviate :atm:                                                             🏧
abbreviate :chart:                                                           💹
abbreviate :heavy_dollar_sign:                                               💲
abbreviate :currency_exchange:                                               💱
abbreviate :copyright:                                                        ©️ 
abbreviate :registered:                                                       ®️ 
abbreviate :tm:                                                               ™️ 
abbreviate :x:                                                                ❌ 
abbreviate :bangbang:                                                         ‼️ 
abbreviate :interrobang:                                                      ⁉️ 
abbreviate :exclamation:                                                      ❗ 
abbreviate :heavy_exclamation_mark:                                           ❗ 
abbreviate :question:                                                         ❓ 
abbreviate :grey_exclamation:                                                 ❕ 
abbreviate :grey_question:                                                    ❔ 
abbreviate :o:                                                                ⭕ 
abbreviate :top:                                                             🔝
abbreviate :end:                                                             🔚
abbreviate :back:                                                            🔙
abbreviate :on:                                                              🔛
abbreviate :soon:                                                            🔜
abbreviate :arrows_clockwise:                                                🔃
abbreviate :clock12:                                                         🕛
abbreviate :clock1230:                                                       🕧
abbreviate :clock1:                                                          🕐
abbreviate :clock130:                                                        🕜
abbreviate :clock2:                                                          🕑
abbreviate :clock230:                                                        🕝
abbreviate :clock3:                                                          🕒
abbreviate :clock330:                                                        🕞
abbreviate :clock4:                                                          🕓
abbreviate :clock430:                                                        🕟
abbreviate :clock5:                                                          🕔
abbreviate :clock530:                                                        🕠
abbreviate :clock6:                                                          🕕
abbreviate :clock7:                                                          🕖
abbreviate :clock8:                                                          🕗
abbreviate :clock9:                                                          🕘
abbreviate :clock10:                                                         🕙
abbreviate :clock11:                                                         🕚
abbreviate :clock630:                                                        🕡
abbreviate :clock730:                                                        🕢
abbreviate :clock830:                                                        🕣
abbreviate :clock930:                                                        🕤
abbreviate :clock1030:                                                       🕥
abbreviate :clock1130:                                                       🕦
abbreviate :heavy_multiplication_x:                                           ✖️ 
abbreviate :heavy_plus_sign:                                                  ➕ 
abbreviate :heavy_minus_sign:                                                 ➖ 
abbreviate :heavy_division_sign:                                              ➗ 
abbreviate :spades:                                                           ♠️ 
abbreviate :hearts:                                                           ♥️ 
abbreviate :clubs:                                                            ♣️ 
abbreviate :diamonds:                                                         ♦️ 
abbreviate :white_flower:                                                    💮
abbreviate :100:                                                             💯
abbreviate :heavy_check_mark:                                                 ✔️ 
abbreviate :ballot_box_with_check:                                            ☑️ 
abbreviate :radio_button:                                                    🔘
abbreviate :link:                                                            🔗
abbreviate :curly_loop:                                                       ➰ 
abbreviate :wavy_dash:                                                       〰️
abbreviate :part_alternation_mark:                                           〽️
abbreviate :trident:                                                         🔱
abbreviate :black_medium_square:                                              ◼️ 
abbreviate :white_medium_square:                                              ◻️ 
abbreviate :black_medium_small_square:                                        ◾ 
abbreviate :white_medium_small_square:                                        ◽ 
abbreviate :black_small_square:                                               ▪️ 
abbreviate :white_small_square:                                               ▫️ 
abbreviate :small_red_triangle:                                              🔺
abbreviate :black_square_button:                                             🔲
abbreviate :white_square_button:                                             🔳
abbreviate :black_circle:                                                     ⚫ 
abbreviate :white_circle:                                                     ⚪ 
abbreviate :red_circle:                                                      🔴
abbreviate :large_blue_circle:                                               🔵
abbreviate :small_red_triangle_down:                                         🔻
abbreviate :white_large_square:                                               ⬜ 
abbreviate :black_large_square:                                               ⬛ 
abbreviate :large_orange_diamond:                                            🔶
abbreviate :large_blue_diamond:                                              🔷
abbreviate :small_orange_diamond:                                            🔸
abbreviate :small_blue_diamond:                                              🔹
